#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi


# Redirect output to stderr.
exec 1>&2

warn () {
	printf '\e[1;31m%s\e[0m\n' "$1"
}

format_err=0
check_err=0
ret=0

echo 'Running "ruff format --check"'
ruff format --check

if [ "$?" -eq 1 ]; then
	format_err=1
	ret=1
fi

echo 'Running "ruff check"'
ruff check

if [ "$?" -eq 1 ]; then
	check_err=1
	ret=1
fi

if [ "${ret}" -eq 1 ] ; then
	echo
fi

if [ "${format_err}" -eq 1 ] ; then
	warn 'Run "ruff format" before committing'
fi

if [ "${check_err}" -eq 1 ] ; then
	warn 'Correct ruff errors before committing'
fi

exit $ret
